### ISSUE TITLE
file is not found

### ISSUE THREAD

**Issue by algorithm3d** [HiroIshida/detic_ros#53]
hi, where is the detic.py in node.py & wrap.py directory? thanks!

**Comment by HiroIshida** [comment]
see https://github.com/HiroIshida/detic_ros/tree/master/node_script

**Comment by algorithm3d** [comment]
yeah, this line in wrapper.py. => "from detic.predictor import VisualizationDemo"

**Comment by HiroIshida** [comment]
oh, I now see your question. 
The symbolic link of the Detic is created inside the node_script in the time of building the docker image.

https://github.com/HiroIshida/detic_ros/blob/4afc32aa2fab3ed19ec05c56ab778e07d591ac4e/Dockerfile#L97
https://github.com/HiroIshida/detic_ros/blob/4afc32aa2fab3ed19ec05c56ab778e07d591ac4e/prepare.sh#L9
